plugins:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - Appraisals
    - gemfiles/**/*
    - lib/generators/ductwork/install/templates/db/*.rb
    - vendor/**/*

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*_spec.rb

Lint/EmptyClass:
  AllowComments: true

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - lib/ductwork/testing/rspec.rb

Naming/BlockForwarding:
  EnforcedStyle: explicit

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/ductwork/models/**/*.rb

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  AllowComments: true

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
