plugins:
  - rubocop-factory_bot

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*_spec.rb

Lint/EmptyClass:
  AllowComments: true

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

RSpec/ExampleLength:
  Max: 35

RSpec/MultipleExpectations:
  Max: 10

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/ductwork/models/**/*.rb

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
