require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Gemspec/RequireMFA:
  Enabled: false

Lint/EmptyClass:
  AllowComments: true

Metrics/MethodLength:
  Max: 30

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

RSpec/ExampleLength:
  Max: 35

RSpec/MultipleExpectations:
  Max: 10

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
